version: '3.4'

services:
  twts-api:
    image: twts-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
  postgres:
    image: postgres:14.5-bullseye
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=twts
